FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build
WORKDIR /app

# copy csproj and restore as distinct layer
COPY src/ ./src/
COPY test/ ./test/

WORKDIR /app/src
RUN dotnet build
WORKDIR /app/test
RUN dotnet test
WORKDIR /app/src
RUN dotnet publish -c Release -o out

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1 AS runtime
COPY bin/Release/netcoreapp3.1/publish/ App/
WORKDIR /app
COPY --from=build /app/src/out ./
ENTRYPOINT ["dotnet", "SuperService.dll"]