FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build
COPY src src/
COPY test /test

WORKDIR /src
RUN dotnet build SuperService.csproj
WORKDIR /test
RUN dotnet test SuperService.UnitTests.csproj 
WORKDIR /src
RUN dotnet publish -c Release -o out

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1 AS runtime
COPY https/ https/
WORKDIR /app
COPY --from=build /src/out ./
ENTRYPOINT ["dotnet", "SuperService.dll"]